### PR TITLE
make testsuite/do_tests.sh return an error in case of error in a test,

### PR DESCRIPTION
**Pull request by apeyser**
and not just for an error in the script itself.

Also remove testsuite/do_test.sh which was mistakenly
included

### CODE REVIEW

**Comment by apeyser** [comment]
This is associated with issue #5 
It passed travis, so how do we get a review and a merge now?

**Comment by jougs** [comment]
I think by everyone not ignoring this ticket ;-) I'll review the request and comment on it.

**Comment by tammoippen** [comment]
Hello,

I have summarized the Guidelines as far as I understand them. Please have a look.

https://www.dropbox.com/s/fc4br3deb60w3p8/NEST%20Coding%20Guidelines.html?dl=0

This is the generated HTML. The original is in markdown.

Best,
Tammo

---

Tammo Ippen

Institute of Neuroscience and Medicine (INM-6)
Computational and Systems Neuroscience
Institute for Advanced Simulation (IAS-6)
Jülich Research Centre and JARA

## 52425 Jülich, Germany

Phone: +49 2461 61-96482
Email: t.ippen@fz-juelich.de
WWW: http://www.csn.fz-juelich.de/

**Comment by jougs** [comment]
Attention please!

Tammo, I guess you did not actually want to comment on this pull request, but rather write a new mail to the people in the migration team. This is apparently something we need to document as well, as I assume that people will otherwise make the same mistake again. Thanks for raising awareness ;-)

**Comment by apeyser** [comment]
And how do we make people aware of the successful merge & pull request here?
I responded to the critique by updating the branch and then running travis; the next step would be for the original reviewers to check this again and give a thumbs up/down, I figure. Then the "someone" needs to actually run the pull request.

**Comment by apeyser** [comment]
Woohoo!

**Pull request merged**
